export const REQUEST_POSITION = 'REQUEST_POSITION';
export const RECEIVE_POSITION = 'RECEIVE_POSITION';
export const COULNDT_RECEIVE_POSITION = 'COULNDT_RECEIVE_POSITION';
export const REQUEST_WEATHER = 'REQUEST_WEATHER';
export const RECEIVE_WEATHER = 'RECEIVE_WEATHER';
export const COULNDT_RECEIVE_WEATHER = 'COULNDT_RECEIVE_WEATHER';
